### ISSUE TITLE
Mozzart crashes at start

### ISSUE THREAD

**Issue by Lelenaic** [weview-app/bozz#2]
OS: macOS Mojave 10.14.1

Sometimes, when I start Mozzart, it randomly crashes for no reason.

Here are the logs:
 ```
2018-11-09 10:16:13.870 [mozzart] All processes are running
2018-11-09 10:16 node[3457] (FSEvents.framework) FSEventStreamStart: register_with_server: ERROR: f2d_register_rpc() => (null) (-22)
2018-11-09 10:16 node[3457] (FSEvents.framework) FSEventStreamStart: register_with_server: ERROR: f2d_register_rpc() => (null) (-22)
2018-11-09 10:16 node[3457] (FSEvents.framework) FSEventStreamStart: register_with_server: ERROR: f2d_register_rpc() => (null) (-22)
2018-11-09 10:16 node[3457] (FSEvents.framework) FSEventStreamStart: register_with_server: ERROR: f2d_register_rpc() => (null) (-22)
2018-11-09 10:16 node[3457] (FSEvents.framework) FSEventStreamStart: register_with_server: ERROR: f2d_register_rpc() => (null) (-22)
2018-11-09 10:16 node[3457] (FSEvents.framework) FSEventStreamStart: register_with_server: ERROR: f2d_register_rpc() => (null) (-22)
events.js:165
      throw er; // Unhandled 'error' event
      ^

Error: Error watching file for changes: EMFILE
    at FSEvent.FSWatcher._handle.onchange (fs.js:1379:9)
Emitted 'error' event at:
    at FSWatcher.<anonymous> (/Users/lenaicgrolleau/.config/yarn/global/node_modules/node-watch/lib/watch.js:265:12)
    at FSWatcher.emit (events.js:180:13)
    at FSEvent.FSWatcher._handle.onchange (fs.js:1382:12)
```

**Comment by fleebzz** [comment]
Please see https://github.com/fleebzz/mozzart for `mozzart` issues

**Comment by fleebzz** [comment]
Please see https://github.com/fleebzz/mozzart for `mozzart` issues
